# Generated by Django 4.2.2 on 2023-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='link',
            new_name='img_link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='src_link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='img_link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
