# Generated by Django 4.2.2 on 2023-06-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_img_link_alter_book_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookapp.setting'),
        ),
        migrations.AlterField(
            model_name='book',
            name='src_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='img_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
