# Generated by Django 4.2.3 on 2023-07-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='books/')),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='RPG_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='settings/')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='library_app.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='rpg_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_app.rpg_setting'),
        ),
    ]
