# Generated by Django 4.2.3 on 2023-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RPG_Setting',
            new_name='RPGSetting',
        ),
    ]
