# Generated by Django 4.2.3 on 2023-07-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_rpg_setting_rpgsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpgsetting',
            options={'verbose_name': 'RPG Setting', 'verbose_name_plural': 'RPG Settings'},
        ),
        migrations.AlterField(
            model_name='rpgsetting',
            name='image',
            field=models.ImageField(upload_to='rpg_settings/'),
        ),
    ]
